// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Bodyfat_ML_projektML.Model
{
    public class ModelInput
    {
        [ColumnName("Density"), LoadColumn(0)]
        public float Density { get; set; }


        [ColumnName("BodyFat"), LoadColumn(1)]
        public float BodyFat { get; set; }


        [ColumnName("Age"), LoadColumn(2)]
        public float Age { get; set; }


        [ColumnName("Weight"), LoadColumn(3)]
        public float Weight { get; set; }


        [ColumnName("Height"), LoadColumn(4)]
        public float Height { get; set; }


        [ColumnName("Neck"), LoadColumn(5)]
        public float Neck { get; set; }


        [ColumnName("Chest"), LoadColumn(6)]
        public float Chest { get; set; }


        [ColumnName("Abdomen"), LoadColumn(7)]
        public float Abdomen { get; set; }


        [ColumnName("Hip"), LoadColumn(8)]
        public float Hip { get; set; }


        [ColumnName("Thigh"), LoadColumn(9)]
        public float Thigh { get; set; }


        [ColumnName("Knee"), LoadColumn(10)]
        public float Knee { get; set; }


        [ColumnName("Ankle"), LoadColumn(11)]
        public float Ankle { get; set; }


        [ColumnName("Biceps"), LoadColumn(12)]
        public float Biceps { get; set; }


        [ColumnName("Forearm"), LoadColumn(13)]
        public float Forearm { get; set; }


        [ColumnName("Wrist"), LoadColumn(14)]
        public float Wrist { get; set; }


    }
}
