// This file was auto-generated by ML.NET Model Builder. 

using System;
using Bodyfat_ML_projektML.Model;

namespace Bodyfat_ML_projektML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Density = 1.0708F,
                Age = 23F,
                Weight = 154.25F,
                Height = 67.75F,
                Neck = 36.2F,
                Chest = 93.1F,
                Abdomen = 85.2F,
                Hip = 94.5F,
                Thigh = 59F,
                Knee = 37.3F,
                Ankle = 21.9F,
                Biceps = 32F,
                Forearm = 27.4F,
                Wrist = 17.1F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual BodyFat with predicted BodyFat from sample data...\n\n");
            Console.WriteLine($"Density: {sampleData.Density}");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Weight: {sampleData.Weight}");
            Console.WriteLine($"Height: {sampleData.Height}");
            Console.WriteLine($"Neck: {sampleData.Neck}");
            Console.WriteLine($"Chest: {sampleData.Chest}");
            Console.WriteLine($"Abdomen: {sampleData.Abdomen}");
            Console.WriteLine($"Hip: {sampleData.Hip}");
            Console.WriteLine($"Thigh: {sampleData.Thigh}");
            Console.WriteLine($"Knee: {sampleData.Knee}");
            Console.WriteLine($"Ankle: {sampleData.Ankle}");
            Console.WriteLine($"Biceps: {sampleData.Biceps}");
            Console.WriteLine($"Forearm: {sampleData.Forearm}");
            Console.WriteLine($"Wrist: {sampleData.Wrist}");
            Console.WriteLine($"\n\nPredicted BodyFat: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
